Repository NITSkmOS/Algorithms, pull requests merged in 2018-10, with the labels that each got.

#129 CODE_OF_CONDUCT.md: Add CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: process/pending_review

#139 Added Binary Search Algorithm and updated ReadMe
  README.md
  binary_search/Cpp/binary_search.cpp
Labels: difficulty/low, hacktoberfest, lang/C++, process/pending_review, type/algo

#138 euclidean_gcd.c: Add Euclidean gcd Algorithm
  README.md
  euclidean_gcd/C/euclidean_gcd.c
Labels: difficulty/medium, hacktoberfest, lang/C, process/pending_review, type/algo

#140 shell_sort.py: Add Shell Sort Algorithm
  README.md
  shell_sort/Python/shell_sort.py
Labels: difficulty/low, hacktoberfest, lang/Python, process/pending_review, type/algo

#144 Add Bubble Sort in C
  README.md
  bubble_sort/C/bubble_sort.c
Labels: difficulty/medium, hacktoberfest, lang/C, process/pending_review, type/algo

#148 Heap sort
  README.md
  heap_sort/python/heap_sort.py
Labels: difficulty/medium, hacktoberfest, lang/Python, process/pending_review, type/algo

#169 Adds the code for AVL Tree in Python
  README.md
  avl_tree/Python/avl_tree.py
Labels: difficulty/medium, hacktoberfest, lang/Python, type/data structure

#248 README.md: Remove codacy badge, Add travis badge
  README.md
Labels: difficulty/newcomer, documentation, process/approved

#268 Add Maximum SubArray Problem[Python]
  README.md
  maximum_subarray/Python/max_sub_array.py
Labels: difficulty/low, hacktoberfest, lang/Python, process/pending_review, process/wip, type/data structure

#372 knapsack.py : Add KnapSack Problem
  README.md
  knapsack_problem/Python/knapsack.py
Labels: difficulty/low, enhancement, hacktoberfest, lang/Python, process/approved, type/algo

#298 radix_sort.cpp: Add Radix Sort Algorithm
  README.md
  radix_sort/Cpp/radix_sort.cpp
Labels: difficulty/low, hacktoberfest, lang/C++, process/pending_review, type/algo

#427 merge_sort.c: Add Merge Sort in C
  README.md
  merge_sort/C/merge_sort.c
Labels: difficulty/low, enhancement, hacktoberfest, lang/C, process/pending_review, type/algo

#426 counting_sort.c: Add Counting Sort Algorithm
  README.md
  counting_sort/C/counting_sort.c
Labels: difficulty/low, hacktoberfest, lang/C, process/approved, type/algo

#432 linked_list.cpp : Add linked list in C++
  README.md
  linked_list/cpp/linked_list.cpp
Labels: difficulty/low, hacktoberfest, lang/C++, process/pending_review, type/data structure

#300 Raise exception when popping from an empty stack #294
  stack/Python/stack.py
Labels: bug, difficulty/low, hacktoberfest, lang/Python, process/pending_review, type/data structure

#434 binary_search_tree.cpp: Add Binary search tree
  README.md
  binary_search_tree/Cpp/binary_search_tree.cpp
Labels: difficulty/low, hacktoberfest, lang/C++, process/pending_review, process/wip, type/data structure

#163 selection_sort.c: Add Selection Sort in C
  README.md
  selection_sort/C/selection_sort.c
Labels: difficulty/low, hacktoberfest, lang/C, process/approved, type/algo

#439 bubble_sort.py: Add BubbleSort Algo
  README.md
  bubble_sort/Python/bubble_sort.py
Labels: difficulty/medium, hacktoberfest, lang/Python, process/approved, type/algo

#445 avl_tree.cpp: Add AVL tree
  README.md
  avl_tree/Cpp/avl_tree.cpp
Labels: difficulty/medium, hacktoberfest, lang/C++, process/approved, size/L, type/data structure

#462 .travis.yml: Activate TravisBuddy
  .travis.yml
Labels: difficulty/low, hacktoberfest, process/approved, size/XS

#468 Add Doubly Linked List DS
  README.md
  doubly_linked_list/c/doubly_linked_list.c
Labels: difficulty/low, hacktoberfest, lang/C, process/approved, size/XS, type/data structure

#477 Adds MergeSort Algorithm in Java
  README.md
  merge_sort/Java/merge_sort.java
Labels: difficulty/low, enhancement, hacktoberfest, lang/Java, process/approved, size/XS, type/algo

#481 New badges for README.md
  README.md
Labels: documentation, hacktoberfest, process/approved, size/XS

#217 Add fenwick_tree.cpp
  README.md
  fenwick_tree/cpp/fenwick_tree.cpp
Labels: difficulty/low, enhancement, hacktoberfest, lang/C++, process/approved, size/XS, type/data structure

#496 README.md: Update badge
  README.md
Labels: bug, difficulty/low, documentation, hacktoberfest, process/approved, size/XS

#483 selection_sort.cpp: Add cpp implementation for selection sort.
  README.md
  selection_sort/Cpp/selection_sort.cpp
Labels: difficulty/low, hacktoberfest, lang/C++, process/approved, size/XS, type/algo

#492 merge_sort.cpp: Add cpp merge sort.
  README.md
  merge_sort/Cpp/merge_sort.cpp
Labels: difficulty/low, enhancement, hacktoberfest, lang/C++, process/approved, size/XS, type/algo

#506 quicksort.java Add Quicksort Algorithm
  README.md
  quicksort/Java/quicksort.java
Labels: difficulty/low, enhancement, hacktoberfest, process/approved, size/XS, type/algo
